/**
 * Regenerates South America outline paths from Natural Earth (world-atlas).
 *
 *   bun run gen:south-america-map
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { geoMercator, geoPath } from "d3-geo";
import { feature } from "topojson-client";

type Topology = {
  objects: {
    countries: object;
  };
};

type CountryFeature = {
  id?: string | number;
  properties: { name: string; code?: string };
  type: string;
  geometry: object;
};

const SOURCE_URL =
  "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json";
const CACHE_PATH = "./scripts/tmp-sa-map/countries-50m.json";

async function loadTopology(): Promise<Topology> {
  try {
    return JSON.parse(readFileSync(CACHE_PATH, "utf8")) as Topology;
  } catch {
    mkdirSync("./scripts/tmp-sa-map", { recursive: true });
    const response = await fetch(SOURCE_URL);
    if (!response.ok) {
      throw new Error(`Failed to download ${SOURCE_URL}: ${response.status}`);
    }
    const text = await response.text();
    writeFileSync(CACHE_PATH, text);
    return JSON.parse(text) as Topology;
  }
}

const topo = await loadTopology();

const countries = feature(
  topo as never,
  topo.objects.countries as never,
) as unknown as {
  features: CountryFeature[];
};

const SA: Record<string, string> = {
  AR: "032",
  BO: "068",
  BR: "076",
  CL: "152",
  CO: "170",
  EC: "218",
  GY: "328",
  PY: "600",
  PE: "604",
  SR: "740",
  UY: "858",
  VE: "862",
};

const byId = new Map(
  countries.features.map((f) => [String(f.id).padStart(3, "0"), f]),
);

const features = Object.entries(SA).map(([code, id]) => {
  const f = byId.get(id);
  if (!f) throw new Error(`Missing ${code}`);
  return {
    ...f,
    properties: { ...f.properties, code },
  };
});

const collection = { type: "FeatureCollection" as const, features };

const width = 560;
const height = 720;
const projection = geoMercator().fitExtent(
  [
    [12, 12],
    [width - 12, height - 12],
  ],
  collection as never,
);
const path = geoPath(projection);

const paths = features.map((f) => {
  const d = path(f as never);
  if (!d) throw new Error(`No path for ${f.properties.code}`);
  return {
    code: f.properties.code as string,
    name: f.properties.name,
    d,
  };
});

const order = [
  "BR",
  "AR",
  "PE",
  "CO",
  "BO",
  "CL",
  "VE",
  "PY",
  "EC",
  "UY",
  "GY",
  "SR",
];
paths.sort((a, b) => order.indexOf(a.code) - order.indexOf(b.code));

mkdirSync("./public/BFV/assets", { recursive: true });

const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" fill="none">
${paths.map((p) => `  <path id="${p.code}" data-name="${p.name}" d="${p.d}" />`).join("\n")}
</svg>
`;

writeFileSync("./public/BFV/assets/south-america-map.svg", svg);

const ts = `/** Auto-generated by scripts/generate-south-america-map.ts — do not edit by hand. */
export const SOUTH_AMERICA_MAP = {
  viewBox: "0 0 ${width} ${height}",
  countries: [
${paths
  .map(
    (p) =>
      `    { code: "${p.code}" as const, name: "${p.name}", d: ${JSON.stringify(p.d)} },`,
  )
  .join("\n")}
  ],
} as const;

export type SouthAmericaCountryCode =
  (typeof SOUTH_AMERICA_MAP.countries)[number]["code"];
`;

writeFileSync("./src/lib/south-america-map.ts", ts);
console.log(
  "Wrote",
  paths.length,
  "countries:",
  paths.map((p) => p.code).join(", "),
);
